### ISSUE TITLE
Vagrant does not work push

### ISSUE THREAD

**Issue by pluhin** [pluhin/sa.it-academy.by#1033]
```
04.Vagrant/5 [ vagrant cloud publish --release pluhin/test 1.1.2 virtualbox /tmp/test.box
You are about to publish a box on Vagrant Cloud with the following options:
pluhin/test:   (v1.1.2) for provider 'virtualbox'
Automatic Release:     true
Do you wish to continue? [y/N] y
==> cloud: Creating a box entry...
Traceback (most recent call last):
	17: from /usr/bin/vagrant:23:in `<main>'
	16: from /usr/bin/vagrant:23:in `load'
	15: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/bin/vagrant:177:in `<top (required)>'
	14: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	13: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	12: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/commands/cloud/root.rb:73:in `execute'
	11: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/commands/cloud/publish.rb:77:in `execute'
	10: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/commands/cloud/publish.rb:113:in `publish_box'
	 9: from /usr/lib/ruby/vendor_ruby/vagrant_cloud/box.rb:92:in `create'
	 8: from /usr/lib/ruby/vendor_ruby/vagrant_cloud/client.rb:52:in `request'
	 7: from /usr/lib/ruby/vendor_ruby/restclient/request.rb:52:in `execute'
	 6: from /usr/lib/ruby/vendor_ruby/restclient/request.rb:145:in `execute'
	 5: from /usr/lib/ruby/vendor_ruby/restclient/request.rb:715:in `transmit'
	 4: from /usr/lib/ruby/2.7.0/net/http.rb:932:in `start'
	 3: from /usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
	 2: from /usr/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
	 1: from /usr/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: no protocols available (OpenSSL::SSL::SSLError)

```

**Comment by pluhin** [comment]
Looks like problem in disabled old SSL protocols in Ubuntu latest versions 

https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level

**Comment by pluhin** [comment]
Problem has been solved:

1. Changes added to ssl config file (mentioned in above comment)
2. Upgrade 
3. Restart

Result is:

```
/tmp [ vagrant cloud publish --release pluhin/test 1.1.2 virtualbox /tmp/test.box               ] 10:43 PM
You are about to publish a box on Vagrant Cloud with the following options:
pluhin/test:   (v1.1.2) for provider 'virtualbox'
Automatic Release:     true
Do you wish to continue? [y/N]y
Saving box information...
Uploading provider with file /tmp/test.box
Complete! Published pluhin/test
Box:              pluhin/test
Description:      
Private:          no
Created:          2020-11-26T19:52:14.907+01:00
Updated:          2020-11-26T19:55:23.476+01:00
Current Version:  1.1.2
Versions:         1.1.2
Downloads:        0
```
